package com.ustadmobile.libuicompose.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB30C7A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD8E7)
val md_theme_light_onPrimaryContainer = Color(0xFF3D0026)
val md_theme_light_secondary = Color(0xFF984061)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onSecondaryContainer = Color(0xFF3E001D)
val md_theme_light_tertiary = Color(0xFF006874)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF97F0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F24)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFF1DEE4)
val md_theme_light_onSurfaceVariant = Color(0xFF504348)
val md_theme_light_outline = Color(0xFF827378)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFFFAFD4)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB30C7A)
val md_theme_light_outlineVariant = Color(0xFFD4C2C8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFAFD4)
val md_theme_dark_onPrimary = Color(0xFF620041)
val md_theme_dark_primaryContainer = Color(0xFF8B005D)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD8E7)
val md_theme_dark_secondary = Color(0xFFFFB1C8)
val md_theme_dark_onSecondary = Color(0xFF5E1133)
val md_theme_dark_secondaryContainer = Color(0xFF7B2949)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_tertiary = Color(0xFF4FD8EB)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF004F58)
val md_theme_dark_onTertiaryContainer = Color(0xFF97F0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF504348)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C2C8)
val md_theme_dark_outline = Color(0xFF9D8D92)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFFB30C7A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFAFD4)
val md_theme_dark_outlineVariant = Color(0xFF504348)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFAD0075)


val successLight = Color(0xFF34693F)
val onSuccessLight = Color(0xFFFFFFFF)
val successContainerLight = Color(0xFFB6F1BB)
val onSuccessContainerLight = Color(0xFF00210A)

val successLightMediumContrast = Color(0xFF164D26)
val onSuccessLightMediumContrast = Color(0xFFFFFFFF)
val successContainerLightMediumContrast = Color(0xFF4B8054)
val onSuccessContainerLightMediumContrast = Color(0xFFFFFFFF)

val successLightHighContrast = Color(0xFF00290D)
val onSuccessLightHighContrast = Color(0xFFFFFFFF)
val successContainerLightHighContrast = Color(0xFF164D26)
val onSuccessContainerLightHighContrast = Color(0xFFFFFFFF)

val successDark = Color(0xFF9BD4A0)
val onSuccessDark = Color(0xFF003915)
val successContainerDark = Color(0xFF1B5129)
val onSuccessContainerDark = Color(0xFFB6F1BB)

val successDarkMediumContrast = Color(0xFF9FD9A4)
val onSuccessDarkMediumContrast = Color(0xFF001B07)
val successContainerDarkMediumContrast = Color(0xFF669D6E)
val onSuccessContainerDarkMediumContrast = Color(0xFF000000)

val successDarkHighContrast = Color(0xFFF0FFED)
val onSuccessDarkHighContrast = Color(0xFF000000)
val successContainerDarkHighContrast = Color(0xFF9FD9A4)
val onSuccessContainerDarkHighContrast = Color(0xFF000000)

