@file:Suppress("unused")

package com.ustadmobile.libuicompose.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00629D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCFE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D33)
val md_theme_light_secondary = Color(0xFF526070)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E4F7)
val md_theme_light_onSecondaryContainer = Color(0xFF0E1D2A)
val md_theme_light_tertiary = Color(0xFF695779)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEFDBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF231533)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF99CBFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00629D)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF99CBFF)
val md_theme_dark_onPrimary = Color(0xFF003354)
val md_theme_dark_primaryContainer = Color(0xFF004A78)
val md_theme_dark_onPrimaryContainer = Color(0xFFCFE5FF)
val md_theme_dark_secondary = Color(0xFFB9C8DA)
val md_theme_dark_onSecondary = Color(0xFF243240)
val md_theme_dark_secondaryContainer = Color(0xFF3A4857)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E4F7)
val md_theme_dark_tertiary = Color(0xFFD4BEE6)
val md_theme_dark_onTertiary = Color(0xFF392A49)
val md_theme_dark_tertiaryContainer = Color(0xFF504060)
val md_theme_dark_onTertiaryContainer = Color(0xFFEFDBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF00629D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF99CBFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF15639A)
val UstadTeal = Color(0xFF006D44)
val light_UstadTeal = Color(0xFF006D44)
val light_onUstadTeal = Color(0xFFFFFFFF)
val light_UstadTealContainer = Color(0xFF91F7BD)
val light_onUstadTealContainer = Color(0xFF002111)
val dark_UstadTeal = Color(0xFF75DAA3)
val dark_onUstadTeal = Color(0xFF003921)
val dark_UstadTealContainer = Color(0xFF005232)
val dark_onUstadTealContainer = Color(0xFF91F7BD)


val successLight = Color(0xFF34693F)
val onSuccessLight = Color(0xFFFFFFFF)
val successContainerLight = Color(0xFFB6F1BB)
val onSuccessContainerLight = Color(0xFF00210A)

val successLightMediumContrast = Color(0xFF164D26)
val onSuccessLightMediumContrast = Color(0xFFFFFFFF)
val successContainerLightMediumContrast = Color(0xFF4B8054)
val onSuccessContainerLightMediumContrast = Color(0xFFFFFFFF)

val successLightHighContrast = Color(0xFF00290D)
val onSuccessLightHighContrast = Color(0xFFFFFFFF)
val successContainerLightHighContrast = Color(0xFF164D26)
val onSuccessContainerLightHighContrast = Color(0xFFFFFFFF)

val successDark = Color(0xFF9BD4A0)
val onSuccessDark = Color(0xFF003915)
val successContainerDark = Color(0xFF1B5129)
val onSuccessContainerDark = Color(0xFFB6F1BB)

val successDarkMediumContrast = Color(0xFF9FD9A4)
val onSuccessDarkMediumContrast = Color(0xFF001B07)
val successContainerDarkMediumContrast = Color(0xFF669D6E)
val onSuccessContainerDarkMediumContrast = Color(0xFF000000)

val successDarkHighContrast = Color(0xFFF0FFED)
val onSuccessDarkHighContrast = Color(0xFF000000)
val successContainerDarkHighContrast = Color(0xFF9FD9A4)
val onSuccessContainerDarkHighContrast = Color(0xFF000000)

