package com.ustadmobile.core.domain.blob.upload

import kotlinx.serialization.Serializable

/**
 * A request to upload a batch of blobs
 *
 * @param blobUrls a list of blobs that the clients wants to upload
 * @param batchUuid a UUID (randomly generated by the client) used to identify this upload batch and
 *        facilitate resumption.
 */
@Serializable
data class BlobBatchUploadRequest(
    val blobUrls: List<BlobBatchUploadRequestItem>,
    val batchUuid: String,
)