describe('The admin can switch off content publicly accessible switch', () => {
  it('Ustad Mobile - delete content test', () => {
  cy.clearLocalStorage()
  cy.login('admin','testpass')
  cy.addContent('/home/ustadmobile/StudioProjects/ustadmobile/test-end-to-end/test-files/content/Epub_Content.epub',"ContentPubliclyAccessibleTest")
  cy.wait(2000)
  cy.contains("ContentPubliclyAccessibleTest").parents("*[role='button']").click()
  cy.wait(4000) 
  cy.contains("Edit").click()
  cy.wait(2000) 
  cy.get(".PrivateSwitchBase-input.MuiSwitch-input.css-1m9pwf3").click()
  cy.wait(2000) 
  cy.contains("Done").click()
  cy.wait(4000) 
  cy.enableGuestLoginAndRegistration()
  cy.logout()
  cy.guestLogin()
  cy.contains('Library').click()
  cy.wait(4000)
  //cy.clearLocalStorage()
 })
})
