describe('The admin can add student and  student joins the class using link or code', () => {
  it('Ustad Mobile - add student and  student joins the class using link or code', () => {
  cy.startTestServer()
  cy.login('admin','testpass')
  //cy.addCourse('Test Course')
 // cy.addStudent_Course('Test Course','ajay','kumar','Male','ak','test')
  //cy.addPerson_PeoplePage('sathya','varma','Male','sv','test')
  cy.admin_copyClassCode('Test Course')
  cy.logout()
  cy.reload()
  cy.login('ak','test')
  cy.contains('Courses').click()
  cy.wait(2000)
  cy.logout()
  cy.login('sv','test')
  cy.contains('Courses').click()
  cy.wait(2000)
 })
})
