#!/bin/bash

ant -lib ../../core/lib/com.objfac.ant.preprocess_0.9.1/preprocessor.jar -f update-preproc.xml

if [ "$?" == "0" ]; then
    echo "Success"
else
    echo "Did you run core getlibs yet?  See the README file"
fi

mkdir -p lib/checkout
cd lib/checkout

#checkout the QR Code lib from Git.  
if [ -e qrcode ]; then
    cd qrcode
    git pull
    cd ..
else
    git clone https://github.com/UstadMobile/Open-Source-QR-Code-Library-OMR-Fork.git qrcode
fi
#go back to base directory
cd ../..
pwd

# Temporarily; remove QRCode from J2ME lib to save space
cp -rv lib/checkout/qrcode/src/jp src/

# Attendance functionalities are not supported in J2ME
#rm -r src/com/ustadmobile/core/omr
#rm src/com/ustadmobile/test/core/TestOMR.java

#rm src/com/ustadmobile/core/controller/AttendanceController.java

