package com.ustadmobile.libcache.db.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Generated by a trigger so that DistributedCacheHashTable can observe new entries.
 */
@Entity
data class NewCacheEntry(
    @PrimaryKey
    var cacheEntryKey: String = "",
    var nceUrl: String = "",
)
