# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UstadMobileIOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UstadMobileIOS
  pod "SharkORM"  

  target 'UstadMobileIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UstadMobileIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
