package com.ustadmobile.lib.db.entities

const val TRIGGER_UPSERT = "%UPSERT%"

const val TRIGGER_CONDITION_WHERE_NEWER = "SELECT %NEW_LAST_MODIFIED_GREATER_THAN_EXISTING%"

const val TRIGGER_CONDITION_ETAG_NOT_EQUALS = "SELECT %NEW_ETAG_NOT_EQUAL_TO_EXISTING%"
